cardata = {
    'CAR_ID': int,
    'CAR_NO': str,
    'CAR_STATE': int,
    'LON': float,
    'LAT': float,
    'FIR_PT_N': int,
    'LST_PT_N': int,
    'LOG_TIME': float,
    'ALL_RUN_MILEAGE': float,
    'ALL_PMTD': float,
    'ALL_DH_MILEAGE_P': float,
    'ALL_DH_MILEAGE_D': float,
    'ALL_RUN_TIME': float,
    'ALL_DH_TIME_P': float,
    'ALL_DH_TIME_D': float,
    'ALL_ORDER_COUNT': int,
    'TASK_CUS_ID': int,
    'TASK_ALL_MILEAGE': float,
    'TASK_PMTD': float,
    'TASK_DH_MILEAGE': float,
    'TASK_NOW_MILEAGE': float,
    'TASK_ACCEPTANCE_TIME': int,
    'TASK_GET_ON_TIME': int,
    'TASK_PATH_ID': int,
}

orderdata = {
    'CUS_ID': int,
    'CAR_ID': int,
    'CUS_STATE': int,
    'ON_LON': float,
    'ON_LAT': float,
    'ON_FIR_PT_N': int,
    'ON_LST_PT_N': int,
    'OFF_LON': float,
    'OFF_LAT': float,
    'OFF_FIR_PT_N': int,
    'OFF_LST_PT_N': int,
    'FIR_L_N': int,
    'LST_L_N': int,
    'APPEARANCE_TIME': int,
    'ACCEPTANCE_TIME': int,
    'GET_ON_TIME': int,
    'GET_OFF_TIME': int,
    'DH_MILEAGE': float,
    'PMTD': float,
}
